export enum Resource {
    USER = 'USER',
    CUSTOMER = 'CUSTOMER',
    MINT_REQUEST = 'MINT_REQUEST',
    BURN_REQUEST = 'BURN_REQUEST',
    FREEZE_REQUEST = 'FREEZE_REQUEST',
    BLACKLIST_REQUEST = 'BLACKLIST_REQUEST',
    REFUND_REQUEST = 'REFUND_REQUEST',
    ACTION_REQUEST = 'ACTION_REQUEST',
    CONFIG = 'CONFIG',
}

export enum Action {
    CREATE = 'CREATE',
    READ = 'READ',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
    APPROVE = 'APPROVE',
    REJECT = 'REJECT',
    CANCEL = 'CANCEL',
}