import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

import React from "react";
import Sidebar from '@/components/pages/dash/Sidebar';
import Navbar from "@/components/pages/dash/navbar";
import { authOptions } from "@/lib/authOptions";
import { getServerSession } from "next-auth";
import { redirect } from 'next/navigation';
import { DashPage } from '@/components/pages/dash';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch the session on the server side
  const session = await getServerSession(authOptions);

  if (!session) {
    // Redirect unauthenticated users to the login page
    redirect('/login');
  }

  return (
    <div className={`drawer drawer-mobile lg:drawer-open min-h-screen h-full ${geistMono.className}`}>
      <input id="sidebar-toggle" type="checkbox" className="drawer-toggle" />
      <div className="drawer-content flex flex-col">
        {/* Navbar */}
        {/* <Navbar /> */}
        {/* Main content */}
        <main className="flex-1">
          {children}
        </main>
      </div>
      <div className="drawer-side h-screen">
        <label htmlFor="sidebar-toggle" className="drawer-overlay" />
        {/* Use the Sidebar component */}
        <Sidebar />
      </div>
    </div>
  );
}