import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import React from "react";
import { MdOutlineOpenInNew } from "react-icons/md";
import Link from "next/link";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <div className={`drawer drawer-mobile lg:drawer-open min-h-screen h-full ${geistMono.className}`}>
          <input id="sidebar-toggle" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col">
            {/* Navbar */}
            <div className="w-full navbar bg-base-300">
              <div className="flex-none lg:hidden">
                <label htmlFor="sidebar-toggle" className="btn btn-square btn-ghost">
                  <svg
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                    fill="none"
                  >
                    <path
                      d="M4 6H20M4 12H20M4 18H11"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    ></path>
                  </svg>
                </label>
              </div>
              {/* Search input */}
              <div className="flex-1 px-2 mx-2">
                <div className="relative">
                  <input
                    type="text"
                    placeholder="Search"
                    className="input input-bordered w-full pl-10"
                  />
                  <span className="absolute inset-y-0 left-0 flex items-center pl-3">
                    <svg
                      className="w-5 h-5 text-base-content"
                      viewBox="0 0 24 24"
                      fill="none"
                    >
                      <path
                        d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                    </svg>
                  </span>
                </div>
              </div>
            </div>
            {/* Main content */}
            <main className="flex-1">
              {children}
            </main>
          </div>
          <div className="drawer-side h-screen">
            <label htmlFor="sidebar-toggle" className="drawer-overlay"></label>
            <aside className="w-64 bg-base-100 h-full">
              {/* Sidebar content */}
              <div className="flex flex-col h-full">
                <div className="flex items-center justify-center mt-8">
                  <div className="flex items-center">
                    {/* Logo and title */}
                    <svg
                      className="w-12 h-12"
                      viewBox="0 0 512 512"
                      fill="none"
                    >
                      <path
                        d="M201.694 387.105C231.686 417.098 280.312 417.098 310.305 387.105C325.301 372.109 332.8 352.456 332.8 332.8C332.8 313.144 325.301 293.491 310.305 278.495C295.309 263.498 288 256 275.2 230.4C256 243.2 243.201 320 243.201 345.6C201.694 345.6 179.2 332.8 179.2 332.8C179.2 352.456 186.698 372.109 201.694 387.105Z"
                        fill="currentColor"
                      ></path>
                    </svg>
                    <span className="mx-2 text-2xl font-semibold text-base-content">
                      MNEE Portal
                    </span>
                  </div>
                </div>
                <nav className="mt-6 p-2 flex-1">
                  <Link
                    className="flex items-center px-6 py-2 text-sm font-medium bg-secondary text-secondary-content rounded-lg"
                    href="/"
                  >
                    Dashboard
                  </Link>
                  <a
                    className="flex items-center px-6 py-2 mt-2 text-sm font-medium hover:bg-secondary hover:text-secondary-content rounded-lg"
                    href="/wallet"
                  >
                    Wallet
                  </a>
                  <a
                    className="flex items-center px-6 py-2 mt-2 text-sm font-medium hover:bg-secondary hover:text-secondary-content rounded-lg"
                    href={`${process.env.NEXT_PUBLIC_MNEE_API}/v1/docs`}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Cosigner Docs <MdOutlineOpenInNew className="ml-2" />
                  </a>
                  <a
                    className="flex items-center px-6 py-2 mt-2 text-sm font-medium hover:bg-secondary hover:text-secondary-content rounded-lg"
                    href="#"
                  >
                    Forms
                  </a>
                </nav>
              </div>
            </aside>
          </div>
        </div>
        </Providers>
      </body>
    </html>
  );
}